{
 "title": "Emby",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Name",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "emby_info", "legendFormat": "{{server_name}}" }
   ]
  },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "emby_info", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Operating System",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "emby_info", "legendFormat": "{{operating_system}}" }
   ]
  },
  {
   "title": "Local Address",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "emby_info", "legendFormat": "{{local_address}}" }
   ]
  },
  {
   "title": "WAN Address",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "emby_info", "legendFormat": "{{wan_address}}" }
   ]
  },
  { "title": "Library", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Video",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "emby_library_size{type=~\"series|movies|episodes\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Audio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "emby_library_size{type=~\"songs|artists|albums\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Clients",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "targets": [
    { "expr": "emby_devices" }
   ]
  },
  {
   "title": "Unplayed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "emby_library_size - emby_played",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}